/**
 * Copyright 2023, 2024 Sasha Lišková and Stephanie Beckon
 *
 * This file is part of Transpapers.
 *
 * Transpapers is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later
 * version.
 *
 * Transpapers is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * Transpapers. If not, see <https://www.gnu.org/licenses/>.
 */

import { AlaskaAdministrativeDivision } from "../../types/locality";

const alaskanAdministrativeDivisions: { [key: string]: AlaskaAdministrativeDivision } = {
    Anchorage: {
        court: {
          address: "825 W 4th Ave #2004, Anchorage, AK 99501",
          city: "Anchorage",
          phone: "(907) 274-8611",
          website: "https://courts.alaska.gov/courtdir/3an.htm",
        },
        doesNameChange: true,
        inPersonFiling: true,
        emailFiling: true,
        emailCourt: "3ANcustservemail@akcourts.gov",
        faxFiling: true,
        faxNumber: "(907) 264-0610",
        trueFiling: false,
    },
    Angoon: {
        court: {
          address: "700 Aan Deina Aat Street, Angoon, AK 99820",
          city: "Angoon",
          phone: "(907) 788-3229",
          website: "https://courts.alaska.gov/courtdir/1ag.htm",
        },
        doesNameChange: false,
        inPersonFiling: true,
        emailFiling: true,
        emailCourt: "1SImailbox@akcourts.gov",
        faxFiling: false,
        trueFiling: true,
        /**forwardsTo: "Sitka",*/
    },
    Bethel: {
        court: {
          address: "204 Eddie Hoffman Hwy, Bethel, AK 99559",
          city: "Bethel",
          phone: "(907) 543-2298",
          website: "https://courts.alaska.gov/courtdir/4be.htm",
        },
        doesNameChange: true,
        inPersonFiling: true,
        emailFiling: true,
        emailCourt: "4BEmailbox@akcourts.gov",
        faxFiling: true,
        faxNumber: "(907) 543-4419",
        trueFiling: true,
    },
    Cordova: {
        court: {
          address: "500 Water St, Cordova, AK 99574",
          city: "Cordova",
          phone: "(907) 424-7312",
          website: "https://courts.alaska.gov/courtdir/3co.htm",
        },
        doesNameChange: true,
        inPersonFiling: false,
        emailFiling: true,
        emailCourt: "3COmailbox@akcourts.gov",
        faxFiling: true,
        faxNumber: "(907) 424-7581",
        trueFiling: true,
    },
    "Delta Junction": {
        court: {
          address: "266 Richardson Hwy, Delta Junction, AK 99737",
          city: "Delta Junction",
          phone: "(907) 895-4211",
          website: "https://courts.alaska.gov/courtdir/4dj.htm",
        },
        doesNameChange: true,
        inPersonFiling: true,
        emailFiling: true,
        emailCourt: "4DJmailbox@akcourts.gov",
        faxFiling: true,
        faxNumber: "(907) 895-4204",
        trueFiling: true,
    },
    Dillingham: {
        court: {
          address: "476 Emperor Way, Dillingham, AK 99576",
          city: "Dillingham",
          phone: "(907) 842-5215",
          website: "https://courts.alaska.gov/courtdir/3di.htm",
        },
        doesNameChange: true,
        inPersonFiling: true,
        emailFiling: false,
        faxFiling: false,
        trueFiling: true,
    },
    Fairbanks: {
        court: {
          address: "101 Lacey St, Fairbanks, AK 99701",
          city: "Fairbanks",
          phone: "(907) 452-9277",
          website: "https://courts.alaska.gov/courtdir/4fa.htm",
        },
        doesNameChange: true,
        inPersonFiling: true,
        emailFiling: true,
        emailCourt: "4FAcivil@akcourts.gov",
        faxFiling: true,
        faxNumber: "(907) 452-9330",
        trueFiling: true,
    },
    "Fort Yukon": {
        court: {
          address: "E 3rd Ave, Fort Yukon, AK 99740",
          city: "Fort Yukon",
          phone: "(907) 662-2336",
          website: "https://courts.alaska.gov/courtdir/4fy.htm",
        },
        doesNameChange: false,
        inPersonFiling: true,
        emailFiling: true,
        emailCourt: "4FAcivil@akcourts.gov",
        faxFiling: true,
        faxNumber: "(907) 452-9330",
        trueFiling: true,
        /**forwardsTo: Fairbanks,*/
    },
    Galena: {
        court: {
          address: "167 Burbot Street, Galena AK 99741",
          city: "Galena",
          phone: "(907) 656-1322",
          website: "https://courts.alaska.gov/courtdir/4ga.htm",
        },
        doesNameChange: false,
        inPersonFiling: true,
        emailFiling: true,
        emailCourt: "4FAcivil@akcourts.gov",
        faxFiling: true,
        faxNumber: "(907) 452-9330",
        trueFiling: true,
        /**forwardsTo: Fairbanks,*/
    },
    Glennallen: {
        court: {
          address: "188.5 Glenn Hwy, Glennallen, AK 99588",
          city: "Glennallen",
          phone: "(907) 822-3405",
          website: "https://courts.alaska.gov/courtdir/3gl.htm",
        },
        doesNameChange: true,
        inPersonFiling: true,
        emailFiling: true,
        emailCourt: "3GLMailbox@akcourts.gov",
        faxFiling: true,
        faxNumber: "(907) 822-5364",
        trueFiling: true,
    },
    Homer: {
        court: {
          address: "3670 Lake St Bldg A, Homer, AK 99603",
          city: "Homer",
          phone: "(907) 235-8171",
          website: "https://courts.alaska.gov/courtdir/3ho.htm",
        },
        doesNameChange: true,
        inPersonFiling: true,
        emailFiling: true,
        emailCourt: "3HOmailbox@akcourts.gov",
        faxFiling: true,
        faxNumber: "(907) 235-4257",
        trueFiling: true,
    },
    Hoonah: {
        court: {
          address: "300 Front St, Hoonah, AK 99829",
          city: "Hoonah",
          phone: "(907) 945-3668",
          website: "https://courts.alaska.gov/courtdir/1hn.htm",
        },
        doesNameChange: false,
        inPersonFiling: true,
        emailFiling: true,
        emailCourt: "1JUMailbox@akcourts.gov",
        faxFiling: true,
        faxNumber: "(907) 463-3788",
        trueFiling: true,
        /**forwardsTo: Juneau,*/
    },
    Juneau: {
        court: {
          address: "123 W 4th St #2, Juneau, AK 99801",
          city: "Juneau",
          phone: "(907) 463-4700",
          website: "https://courts.alaska.gov/courtdir/1ju.htm",
        },
        doesNameChange: true,
        inPersonFiling: true,
        emailFiling: true,
        emailCourt: "1JUMailbox@akcourts.gov",
        faxFiling: true,
        faxNumber: "(907) 463-3788",
        trueFiling: true,
    },
    Kenai: {
        court: {
          address: "125 Trading Bay Rd, Kenai, AK 99611",
          city: "Kenai",
          phone: "(907) 283-3110",
          website: "https://courts.alaska.gov/courtdir/3kn.htm",
        },
        doesNameChange: true,
        inPersonFiling: true,
        emailFiling: false,
        faxFiling: false,
        trueFiling: true,
    },
    Ketchikan: {
        court: {
          address: "415 Main St #402, Ketchikan, AK 99901",
          city: "Ketchikan",
          phone: "(907) 225-3141",
          website: "https://courts.alaska.gov/courtdir/1ke.htm",
        },
        doesNameChange: true,
        inPersonFiling: true,
        emailFiling: true,
        emailCourt: "1KEMailbox@akcourts.gov",
        faxFiling: false,
        trueFiling: true,
    },
    Kodiak: {
        court: {
          address: "204 Mission Rd #124, Kodiak, AK 99615",
          city: "Kodiak",
          phone: "(907) 486-1600",
          website: "https://courts.alaska.gov/courtdir/3ko.htm",
        },
        doesNameChange: true,
        inPersonFiling: true,
        emailFiling: false,
        faxFiling: false,
        trueFiling: true,
    },
    Kotzebue: {
        court: {
          address: "605 Third Street, Kotzebue, AK 99752",
          city: "Kotzebue",
          phone: "(907) 442-3208",
          website: "https://courts.alaska.gov/courtdir/2kb.htm",
        },
        doesNameChange: true,
        inPersonFiling: true,
        emailFiling: true,
        emailCourt: "2KBmailbox@akcourts.gov",
        faxFiling: false,
        trueFiling: true,
    },
    Naknek: {
        court: {
          address: "#1 Main Street, Naknek, AK 99633",
          city: "Naknek",
          phone: "(907) 246-4240",
          website: "https://courts.alaska.gov/courtdir/2kb.htm",
        },
        doesNameChange: true,
        inPersonFiling: false,
        emailFiling: true,
        emailCourt: "3NAmailbox@akcourts.gov",
        faxFiling: false,
        trueFiling: true,
    },
    Nenana: {
        court: {
          address: "102 8th St, Nenana, AK 99760",
          city: "Nenana",
          phone: "(907) 832-5430",
          website: "https://courts.alaska.gov/courtdir/4ne.htm",
        },
        doesNameChange: true,
        inPersonFiling: true,
        emailFiling: true,
        emailCourt: "4NEmailbox@akcourts.gov",
        faxFiling: true,
        faxNumber: "(907) 832-5841",
        trueFiling: true,
    },
    Nome: {
        court: {
          address: "306 W 5th Ave, Nome, AK 99762",
          city: "Nome",
          phone: "(907) 443-5216",
          website: "https://courts.alaska.gov/courtdir/2no.htm",
        },
        doesNameChange: true,
        inPersonFiling: true,
        emailFiling: true,
        emailCourt: "2NOmailbox@akcourts.gov",
        faxFiling: false,
        trueFiling: true,
    },
    Palmer: {
        court: {
          address: "435 S Denali St, Palmer, AK 99645",
          city: "Palmer",
          phone: "(907) 746-8181",
          website: "https://courts.alaska.gov/courtdir/3pa.htm",
        },
        doesNameChange: true,
        inPersonFiling: false,
        emailFiling: true,
        emailCourt: "3PAcivil@akcourts.gov",
        faxFiling: false,
        trueFiling: false,
    },
    Petersburg: {
        court: {
          address: "17 N Nordic Dr, Petersburg, AK 99833",
          city: "Petersburg",
          phone: "(907) 772-3824",
          website: "https://courts.alaska.gov/courtdir/1pe.htm",
        },
        doesNameChange: true,
        inPersonFiling: true,
        emailFiling: true,
        emailCourt: "1PEMailbox@akcourts.gov",
        faxFiling: true,
        faxNumber: "(907) 772-3018",
        trueFiling: true,
    },
    "Prince of Wales": {
        court: {
          address: "6738 Klawock Hollis Hwy, Klawock, AK 99925",
          city: "Klawock",
          phone: "(907) 755-8801",
          website: "https://courts.alaska.gov/courtdir/1pw.htm",
        },
        doesNameChange: true,
        inPersonFiling: true,
        emailFiling: true,
        emailCourt: "1PWmailbox@akcourts.gov",
        faxFiling: true,
        faxNumber: "(907) 755-8805",
        trueFiling: true,
    },
    Seward: {
        court: {
          address: "410 Adams St, Seward, AK 99664",
          city: "Seward",
          phone: "(907) 224-3075",
          website: "https://courts.alaska.gov/courtdir/3sw.htm",
        },
        doesNameChange: true,
        inPersonFiling: false,
        emailFiling: true,
        emailCourt: "3SWmailbox@akcourts.gov",
        faxFiling: false,
        trueFiling: true,
    },
    Sitka: {
        court: {
          address: "304 Lake St #203, Sitka, AK 99835",
          city: "Sitka",
          phone: "(907) 747-3291",
          website: "https://courts.alaska.gov/courtdir/1si.htm",
        },
        doesNameChange: true,
        inPersonFiling: false,
        emailFiling: true,
        emailCourt: "1SImailbox@akcourts.gov",
        faxFiling: false,
        trueFiling: true,
    },
    Tok: {
        court: {
          address: "1313.5 Alaska Hwy, Tok, AK 99780",
          city: "Tok",
          phone: "(907) 883-5171",
          website: "https://courts.alaska.gov/courtdir/4to.htm",
        },
        doesNameChange: true,
        inPersonFiling: true,
        emailFiling: true,
        emailCourt: "4TOmailbox@akcourts.gov",
        faxFiling: true,
        faxNumber: "(907) 883-4367",
        trueFiling: true,
    },
    Unalaska: {
        court: {
          address: "204 W Broadway Ave, Unalaska, AK 99685",
          city: "Unalaska",
          phone: "(907) 581-1266",
          website: "https://courts.alaska.gov/courtdir/3un.htm",
        },
        doesNameChange: true,
        inPersonFiling: true,
        emailFiling: true,
        emailCourt: "3UNmailbox@akcourts.gov",
        faxFiling: true,
        faxNumber: "(907) 581-2809",
        trueFiling: false,
    },
    Utqiagvik: {
        court: {
          address: "1250 Agvik St, Utqiagvik, AK 99723",
          city: "Utqiagvik",
          phone: "(907) 852-4800",
          website: "https://courts.alaska.gov/courtdir/2ba.htm",
        },
        doesNameChange: true,
        inPersonFiling: true,
        emailFiling: true,
        emailCourt: "2BAmailbox@akcourts.gov",
        faxFiling: false,
        trueFiling: true,
    },
    Valdez: {
        court: {
          address: "213 Meals Ave, Valdez, AK 99686",
          city: "Valdez",
          phone: "(907) 835-2266",
          website: "https://courts.alaska.gov/courtdir/3va.htm",
        },
        doesNameChange: true,
        inPersonFiling: true,
        emailFiling: true,
        emailCourt: "3VAmailbox@akcourts.gov",
        faxFiling: true,
        faxNumber: "(907) 835-3764",
        trueFiling: true,
    },
    Wrangell: {
        court: {
          address: "431 Zimovia Highway, Wrangell AK 99929",
          city: "Wrangell",
          phone: "(907) 874-2311",
          website: "https://courts.alaska.gov/courtdir/1wr.htm",
        },
        doesNameChange: true,
        inPersonFiling: true,
        emailFiling: false,
        faxFiling: false,
        trueFiling: true,
    },
};